title: Adam Kozakiewicz - Data Analyst portfolio
description: Hi, I am an aspiring data analyst building a portfolio using technologies such as SQL, Python, MS Excel, Tableau. I am looking for a team where I can use my commitment and analytical skills, while learning something new every day. I value teamwork, as well as independently completing tasks assigned to me.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
